//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PXWeb {
    
    
    public partial class FootnotesPresentation {
        
        /// <summary>
        /// TableInformationFootnoteView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PCAxis.Web.Controls.TableInformation TableInformationFootnoteView;
        
        /// <summary>
        /// FootnoteSelectLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PCAxis.Web.Controls.Footnote FootnoteSelectLink;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new PXWeb.Presentation1 Master {
            get {
                return ((PXWeb.Presentation1)(base.Master));
            }
        }
    }
}
