Public Class Plugins

    Public Class Operations
        Public Const PIVOT_MANUAL As String = "pivotManual"
        Public Const PIVOT_CW As String = "pivotCW"
        Public Const PIVOT_CCW As String = "pivotCCW"
        Public Const CHANGE_VALUE_ORDER As String = "changeValueOrder"
        Public Const SPLIT_TIME_VARIABLE As String = "splitTimeVariable"
        Public Const CHANGE_DECIMAL As String = "changeDecimal"
        Public Const DELETE_VALUE As String = "deleteValue"
        Public Const DELETE_VARIABLE As String = "deleteVariable"
        Public Const CHANGE_TEXT_PRESENTATION As String = "changeTextPresentation"
        Public Const CHANGE_TEXT_CODE_PRESENTATION As String = "changeTextCodePresentation"
        Public Const PER_PART As String = "perPart"
        Public Const REMOVE_NO_ROWS As String = "removeNoRows"
        Public Const REMOVE_ZERO_ROWS As String = "removeZeroRows"
        Public Const REMOVE_ZERO_AND_NIL_ROWS As String = "removeZeroAndNilRows"
        Public Const REMOVE_SYMBOL_ROWS As String = "removeSymbolRows"
        Public Const REMOVE_ZERO_NIL_AND_SYMBOL_ROWS As String = "removeZeroNilAndSymbolRows"
        Public Const SUM As String = "sum"
        Public Const SUBTRACT As String = "subtract"
        Public Const DIVIDE As String = "divide"
        Public Const MULTIPLY As String = "multiply"
        Public Const SWITCH_LAYOUT As String = "switchLayout"
    End Class

    Public Class Views
        Public Const TABLE_LAYOUT1 As String = "tableViewLayout1"
        Public Const TABLE_LAYOUT2 As String = "tableViewLayout2"
        Public Const TABLE_SORTED As String = "tableViewSorted"
        Public Const CHART_COLUMN As String = "chartViewColumn"
        Public Const CHART_COLUMNSTACKED As String = "chartViewColumnStacked"
        Public Const CHART_COLUMNSTACKED100 As String = "chartViewColumnStacked100"
        Public Const CHART_BAR As String = "chartViewBar"
        Public Const CHART_BARSTACKED As String = "chartViewBarStacked"
        Public Const CHART_BARSTACKED100 As String = "chartViewBarStacked100"
        Public Const CHART_LINE As String = "chartViewLine"
        Public Const CHART_COLUMNLINE As String = "chartViewColumnLine"
        Public Const CHART_POPULATIONPYRAMID As String = "chartViewPopulationPyramid"
        Public Const CHART_PIE As String = "chartViewPie"
        Public Const CHART_AREA As String = "chartViewArea"
        Public Const CHART_AREASTACKED As String = "chartViewAreaStacked"
        Public Const CHART_AREASTACKED100 As String = "chartViewAreaStacked100"
        Public Const CHART_POINT As String = "chartViewPoint"
        Public Const CHART_RADAR As String = "chartViewRadar"
        Public Const FOOTNOTE As String = "footnoteView"
        Public Const INFORMATION As String = "informationView"
    End Class

    Public Class FileFormats
        Public Const PX As String = "px"
        Public Const PX_PX As String = "FileTypePX"
        Public Const XLS As String = "xls"
        Public Const XLS_EXCEL As String = "FileTypeExcel"
        Public Const XLS_DOUBLE_COLUMN As String = "FileTypeExcelDoubleColumn"
        Public Const CSV As String = "csv"
        Public Const CSV2 As String = "FileTypeCsv2"
        Public Const CSV3 As String = "FileTypeCsv3"
        Public Const CSV_TABULATOR_WITH_HEADING As String = "FileTypeCsvWithHeadingAndTabulator"
        Public Const CSV_TABULATOR_WITHOUT_HEADING As String = "FileTypeCsvWithoutHeadingAndTabulator"
        Public Const CSV_COMMA_WITH_HEADING As String = "FileTypeCsvWithHeadingAndComma"
        Public Const CSV_COMMA_WITHOUT_HEADING As String = "FileTypeCsvWithoutHeadingAndComma"
        Public Const CSV_SPACE_WITH_HEADING As String = "FileTypeCsvWithHeadingAndSpace"
        Public Const CSV_SPACE_WITHOUT_HEADING As String = "FileTypeCsvWithoutHeadingAndSpace"
        Public Const CSV_SEMICOLON_WITH_HEADING As String = "FileTypeCsvWithHeadingAndSemiColon"
        Public Const CSV_SEMICOLON_WITHOUT_HEADING As String = "FileTypeCsvWithoutHeadingAndSemiColon"
        Public Const HTML As String = "html"
        Public Const HTML_HTM As String = "FileTypeHtml"
        Public Const SCB As String = "scb"
        Public Const SCB_RELATIONAL As String = "FileTypeRelational"
        Public Const TXT As String = "txt"
        Public Const TXT_TEXT As String = "FileTypeText"
        Public Const CHART As String = "chart"
        Public Const CHART_PNG As String = "FileTypeChartPng"
        Public Const CHART_GIF As String = "FileTypeChartGif"
        Public Const CHART_JPEG As String = "FileTypeChartJpeg"

    End Class

    Public Class Categories
        Public Const CHART As String = "chart"
        Public Const VIEW As String = "view"
        Public Const OPERATION As String = "operation"
        Public Const NONE As String = ""
    End Class
End Class
