//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:2.0.50727.3634
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace PCAxis.Sql.Pxs {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:pcaxis:pxsquery:version20090416", IsNullable=false)]
    public partial class PxsQuery {
        
        private InformationType informationField;
        
        private QueryType queryField;
        
        private PresentationType presentationField;
        
        private string idField;
        
        /// <remarks/>
        public InformationType Information {
            get {
                return this.informationField;
            }
            set {
                this.informationField = value;
            }
        }
        
        /// <remarks/>
        public QueryType Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        public PresentationType Presentation {
            get {
                return this.presentationField;
            }
            set {
                this.presentationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class InformationType {
        
        private string metaVersionField;
        
        private System.DateTime createdDateField;
        
        private CreatedByType createdByField;
        
        private string commentField;
        
        private InformationTypeFiles filesField;
        
        private InformationTypeBatchOptions batchOptionsField;
        
        private MenuSelType[] menuField;
        
        /// <remarks/>
        public string MetaVersion {
            get {
                return this.metaVersionField;
            }
            set {
                this.metaVersionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public CreatedByType CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public InformationTypeFiles Files {
            get {
                return this.filesField;
            }
            set {
                this.filesField = value;
            }
        }
        
        /// <remarks/>
        public InformationTypeBatchOptions BatchOptions {
            get {
                return this.batchOptionsField;
            }
            set {
                this.batchOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MenuSel", IsNullable=false)]
        public MenuSelType[] Menu {
            get {
                return this.menuField;
            }
            set {
                this.menuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class CreatedByType {
        
        private string userNameField;
        
        private string userIdField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class AxisType {
        
        private int indexField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class PresentationType {
        
        private AxisType[] stubField;
        
        private AxisType[] headingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StubElement", IsNullable=false)]
        public AxisType[] Stub {
            get {
                return this.stubField;
            }
            set {
                this.stubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HeadingElement", IsNullable=false)]
        public AxisType[] Heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class TimeType {
        
        private TimeTypeTimeOption timeOptionField;
        
        private object itemField;
        
        private string timeValField;
        
        private string codeField;
        
        /// <remarks/>
        public TimeTypeTimeOption TimeOption {
            get {
                return this.timeOptionField;
            }
            set {
                this.timeOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoOfValues", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("TimeStart", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("TimeValues", typeof(TimeTypeTimeValues))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public string TimeVal {
            get {
                return this.timeValField;
            }
            set {
                this.timeValField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public enum TimeTypeTimeOption {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class TimeTypeTimeValues {
        
        private BasicValueType[] timeValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TimeValue")]
        public BasicValueType[] TimeValue {
            get {
                return this.timeValueField;
            }
            set {
                this.timeValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValueTypeWithGroup))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class BasicValueType {
        
        private string codeField;
        
        private int sortOrderField;
        
        private bool sortOrderFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int sortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sortOrderSpecified {
            get {
                return this.sortOrderFieldSpecified;
            }
            set {
                this.sortOrderFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class ValueTypeWithGroup : BasicValueType {
        
        private ValueTypeWithGroupGroup groupField;
        
        /// <remarks/>
        public ValueTypeWithGroupGroup Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class ValueTypeWithGroupGroup {
        
        private StringLangType[] groupTextField;
        
        private GroupValueType[] groupValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GroupText")]
        public StringLangType[] GroupText {
            get {
                return this.groupTextField;
            }
            set {
                this.groupTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GroupValue")]
        public GroupValueType[] GroupValue {
            get {
                return this.groupValueField;
            }
            set {
                this.groupValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class StringLangType {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class GroupValueType {
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class SelectionType {
        
        private SelectionTypeMethod methodField;
        
        private SelectionTypeSort sortField;
        
        private SelectionTypeContent contentField;
        
        private SelectionTypeTime timeField;
        
        private SelectionTypeVariable[] variablesField;
        
        /// <remarks/>
        public SelectionTypeMethod Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public SelectionTypeSort Sort {
            get {
                return this.sortField;
            }
            set {
                this.sortField = value;
            }
        }
        
        /// <remarks/>
        public SelectionTypeContent Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public SelectionTypeTime Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Variable", IsNullable=false)]
        public SelectionTypeVariable[] Variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class SelectionTypeMethod {
        
        private SelectionTypeMethodSelectionCriterion selectionCriterionField;
        
        private SelectionTypeMethodSelectionCondition selectionConditionField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SelectionTypeMethodSelectionCriterion selectionCriterion {
            get {
                return this.selectionCriterionField;
            }
            set {
                this.selectionCriterionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SelectionTypeMethodSelectionCondition selectionCondition {
            get {
                return this.selectionConditionField;
            }
            set {
                this.selectionConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public enum SelectionTypeMethodSelectionCriterion {
        
        /// <remarks/>
        Limit,
        
        /// <remarks/>
        Number,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public enum SelectionTypeMethodSelectionCondition {
        
        /// <remarks/>
        Larger,
        
        /// <remarks/>
        Smaller,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class SelectionTypeSort {
        
        private SelectionTypeSortSortBy sortByField;
        
        private SelectionTypeSortSortDirection sortDirectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SelectionTypeSortSortBy sortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SelectionTypeSortSortDirection sortDirection {
            get {
                return this.sortDirectionField;
            }
            set {
                this.sortDirectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public enum SelectionTypeSortSortBy {
        
        /// <remarks/>
        Value,
        
        /// <remarks/>
        Code,
        
        /// <remarks/>
        Text,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public enum SelectionTypeSortSortDirection {
        
        /// <remarks/>
        Ascending,
        
        /// <remarks/>
        Descending,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class SelectionTypeContent {
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class SelectionTypeTime {
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class SelectionTypeVariable {
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class PQVariable {
        
        private string selectedValuesetField;
        
        private string presTextOptionField;
        
        private PQVariableAggregation aggregationField;
        
        private string structureIdField;
        
        private PQVariableValues valuesField;
        
        private string codeField;
        
        /// <remarks/>
        public string SelectedValueset {
            get {
                return this.selectedValuesetField;
            }
            set {
                this.selectedValuesetField = value;
            }
        }
        
        /// <remarks/>
        public string PresTextOption {
            get {
                return this.presTextOptionField;
            }
            set {
                this.presTextOptionField = value;
            }
        }
        
        /// <remarks/>
        public PQVariableAggregation Aggregation {
            get {
                return this.aggregationField;
            }
            set {
                this.aggregationField = value;
            }
        }
        
        /// <remarks/>
        public string StructureId {
            get {
                return this.structureIdField;
            }
            set {
                this.structureIdField = value;
            }
        }
        
        /// <remarks/>
        public PQVariableValues Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public enum PQVariableAggregation {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        H,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class PQVariableValues {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Selection", typeof(SelectionType))]
        [System.Xml.Serialization.XmlElementAttribute("Value", typeof(ValueTypeWithGroup))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class myLanguageType {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="language")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class allType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class QueryType {
        
        private QueryTypeLanguages languagesField;
        
        private string tableSourceField;
        
        private string subTableField;
        
        private QueryTypeContents contentsField;
        
        private PQVariable[] variablesField;
        
        private TimeType timeField;
        
        /// <remarks/>
        public QueryTypeLanguages Languages {
            get {
                return this.languagesField;
            }
            set {
                this.languagesField = value;
            }
        }
        
        /// <remarks/>
        public string TableSource {
            get {
                return this.tableSourceField;
            }
            set {
                this.tableSourceField = value;
            }
        }
        
        /// <remarks/>
        public string SubTable {
            get {
                return this.subTableField;
            }
            set {
                this.subTableField = value;
            }
        }
        
        /// <remarks/>
        public QueryTypeContents Contents {
            get {
                return this.contentsField;
            }
            set {
                this.contentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Variable", IsNullable=false)]
        public PQVariable[] Variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
            }
        }
        
        /// <remarks/>
        public TimeType Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class QueryTypeLanguages {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("All", typeof(allType))]
        [System.Xml.Serialization.XmlElementAttribute("Language", typeof(myLanguageType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class QueryTypeContents {
        
        private BasicValueType[] contentField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Content")]
        public BasicValueType[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class MenuSelType {
        
        private string levelField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class InformationTypeFiles {
        
        private string pxsfileField;
        
        private string outfileField;
        
        private string logfileField;
        
        private string textfileField;
        
        private string sqlfileField;
        
        /// <remarks/>
        public string Pxsfile {
            get {
                return this.pxsfileField;
            }
            set {
                this.pxsfileField = value;
            }
        }
        
        /// <remarks/>
        public string Outfile {
            get {
                return this.outfileField;
            }
            set {
                this.outfileField = value;
            }
        }
        
        /// <remarks/>
        public string Logfile {
            get {
                return this.logfileField;
            }
            set {
                this.logfileField = value;
            }
        }
        
        /// <remarks/>
        public string Textfile {
            get {
                return this.textfileField;
            }
            set {
                this.textfileField = value;
            }
        }
        
        /// <remarks/>
        public string Sqlfile {
            get {
                return this.sqlfileField;
            }
            set {
                this.sqlfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pcaxis:pxsquery:version20090416")]
    public partial class InformationTypeBatchOptions {
        
        private string sqltestField;
        
        private string pxDatabaseField;
        
        private string replaceField;
        
        private string metabaseField;
        
        /// <remarks/>
        public string Sqltest {
            get {
                return this.sqltestField;
            }
            set {
                this.sqltestField = value;
            }
        }
        
        /// <remarks/>
        public string PxDatabase {
            get {
                return this.pxDatabaseField;
            }
            set {
                this.pxDatabaseField = value;
            }
        }
        
        /// <remarks/>
        public string Replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
        
        /// <remarks/>
        public string Metabase {
            get {
                return this.metabaseField;
            }
            set {
                this.metabaseField = value;
            }
        }
    }
}
