'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PCAxis.Web.Controls.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;xs:schema id=&quot;CommandBarPluginSchema&quot; targetNamespace=&quot;http://www.pc-axis.scb.se/CommandBarPluginSchema.xsd&quot;
        '''xmlns=&quot;http://www.pc-axis.scb.se/CommandBarPluginSchema.xsd&quot; attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;xs:element name=&quot;commandBar&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:sequence&gt;
        '''        &lt;xs:element name=&quot;plugins&quot; type=&quot;plugins&quot; maxOccurs=&quot;1&quot; minOccurs=&quot;1&quot; /&gt;
        '''&lt;!--        
        '''		  &lt;xs:element [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CommandBarPluginSchema() As String
            Get
                Return ResourceManager.GetString("CommandBarPluginSchema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;commandBar xmlns=&quot;http://www.pc-axis.scb.se/CommandBarPluginSchema.xsd&quot;&gt;
        '''  &lt;plugins&gt;
        '''    &lt;plugin name=&quot;pivotManual&quot; type=&quot;PCAxis.Web.Controls.Pivot, PCAxis.Web.Controls, Version=1.1.0.0, Culture=neutral, PublicKeyToken=c0a818bde8f95c30&quot; hasUI=&quot;true&quot; nameCode=&quot;CtrlCommandBarFunctionPivotManual&quot; Image=&quot;button_pivot.png&quot; ShortcutImage=&quot;small_button_pivot.gif&quot;&gt;
        '''      &lt;properties&gt;
        '''        &lt;property key=&quot;DownButtonImagePath&quot; value=&quot;MoveDown.gif&quot; /&gt;
        '''        &lt;property  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CommandBarPluginsOperations() As String
            Get
                Return ResourceManager.GetString("CommandBarPluginsOperations", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;commandBar xmlns=&quot;http://www.pc-axis.scb.se/CommandBarPluginSchema.xsd&quot;&gt;
        '''  &lt;plugins&gt;
        '''		&lt;plugin name=&quot;tableViewLayout1&quot; type=&quot;PCAxis.Web.Controls.TableView, PCAxis.Web.Controls, Version=1.1.0.0, Culture=neutral, PublicKeyToken=c0a818bde8f95c30&quot; hasUI=&quot;false&quot; nameCode=&quot;CtrlPresentationViewTableLayout1&quot; Image=&quot;button_layout_1.png&quot; ShortcutImage=&quot;small_button_layout_1.png&quot;&gt;
        '''			 &lt;properties&gt;
        '''				  &lt;property key=&quot;layout&quot; value=&quot;tableViewLayout1&quot; /&gt;
        '''			 &lt;/properties&gt;
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CommandBarPluginsViews() As String
            Get
                Return ResourceManager.GetString("CommandBarPluginsViews", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;FileTypeList xmlns=&quot;http://www.scb.se&quot;
        '''xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        '''xsi:schemaLocation=&quot;http://www.scb.se ../XSDSchemas/FileSchema.xsd&quot;&gt;
        '''	 &lt;FileType Active=&quot;true&quot;&gt;
        '''		  &lt;Type&gt;px&lt;/Type&gt;
        '''		  &lt;AssemblyQualifiedName&gt;PCAxis.Paxiom.PXFileSerializer, PCAxis.Core, Version=1.1.0.0, Culture=neutral, PublicKeyToken=c0a818bde8f95c30&lt;/AssemblyQualifiedName&gt;
        '''      &lt;Creator&gt;PCAxis.Web.Controls.PxFileSerializerCreator, PCAxis.Web.Controls&lt;/Creator&gt;
        '''		  &lt;FileInfos&gt;
        '''			 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FileConfig() As String
            Get
                Return ResourceManager.GetString("FileConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''targetNamespace=&quot;http://www.scb.se&quot;
        '''xmlns=&quot;http://www.scb.se&quot;
        '''elementFormDefault=&quot;qualified&quot;&gt;
        '''	&lt;xs:annotation&gt;
        '''	&lt;xs:appinfo&gt;Version Info&lt;/xs:appinfo&gt;
        '''	&lt;xs:documentation xml:lang=&quot;en&quot;&gt;
        '''		Modified: 2008-12-18
        '''		Version: 1.0
        '''		By: Robert Karlsson Consultant from Logica 
        '''		Description:  First release of this schema.
        '''					  Only the file types existing 
        '''					  at this time are included.
        '''					  Comments added.
        '''	&lt;/xs:docume [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FileSchema() As String
            Get
                Return ResourceManager.GetString("FileSchema", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
